### ISSUE TITLE
[TEST] Add Test `Volume is created from image and create a VM using that volume`

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/tests#1097] opened 2024-02-06 18:31 UTC
## What's the test to develop? Please describe

According to https://github.com/harvester/harvester/issues/4758#issuecomment-1925613014, Vm basic operations failed but we didn't catch this on CI. We need to analyze why we didn't we catch this.
If we don't have respective test cases, we need to implement this on priority.

**Comment by lanfon72** [comment] 2024-02-06 18:54
We don't have those test cases listed in `manual test plans`:
![image](https://github.com/harvester/tests/assets/5169694/d5211ee2-70ac-4eb9-b89a-341171eee335)

Failed cases marked as `e2e_be` is legacy automation tests, which not actually equals to the test plan. (the test plan is based on UI operation)

**Comment by khushboo-rancher** [comment] 2024-02-06 19:03
> Failed cases marked as e2e_be is legacy automation tests, which not actually equals to the test plan.

What's e2e_be? Did you mean these cases need not be added in the test plan for automation?

The failed scenarios due to bumping  kubevirt to v1.1.0 https://github.com/harvester/harvester/issues/5020 and https://github.com/harvester/harvester/issues/5076 should be covered in the automation backend test cases.

**Comment by lanfon72** [comment] 2024-02-06 19:25
> > Failed cases marked as e2e_be is legacy automation tests, which not actually equals to the test plan.
> 
> What's e2e_be? Did you mean these cases need not be added in the test plan for automation?
> 
> The failed scenarios due to bumping kubevirt to v1.1.0 [harvester/harvester#5020](https://github.com/harvester/harvester/issues/5020) and [harvester/harvester#5076](https://github.com/harvester/harvester/issues/5076) should be covered in the automation backend test cases.

The `e2e_be` marked that it would be covered by legacy automation code ideally, but actually, most manual test plan marked with `e2e_be` is not covered correctly.

For issue#5020, we were discussed in QA meeting that Albin hit this bug which caused by Longhorn[^1] and already fixed in latest Harvester.  In automation test, we only test that the volume could be created from image,[^2] but **NOT** test whether it is able to create any VMs, the test case rewrote based on legacy code with same test steps.

For issue #5076, upgrade testing **will not** test VM migration during upgrading, that's the reason why automation didn't catch the bug.

[^1]: https://github.com/harvester/harvester/issues/5020#issuecomment-1910374584
[^2]: https://github.com/harvester/tests/blob/2ac7f68a836ed317291861085cb37d4dc2bafad9/harvester_e2e_tests/integrations/test_1_volumes.py#L81

**Comment by khushboo-rancher** [comment] 2024-02-06 19:32
Got it. To summarize we'll have to implement below two cases in automation.
1. Test Volume is created from image and create a VM using that volume. (Let's track this scenario implementation with this ticket.)
2. While upgrading, testing the VM is migrated successfully. (Let's create a ticket to track that.)

**Comment by lanfon72** [comment] 2024-02-06 19:39
please update the title and content to relevant topic, thanks.

**Comment by lanfon72** [comment] 2024-07-29 14:52
close as the test case passed in several builds.

**Closed by lanfon72** 2024-07-29 14:52 UTC
Labels: area/backend-automation, priority/0
